import test from 'node:test';
import assert from 'node:assert/strict';
import {FORMATS,BOOST_MAX,boostCost,migrateMenu,chooseFormat,milestone,prestigeOffer,elapsedSteps} from '../src/depth.js';
import {migrateProgression,customerType,satisfyCustomer,saleMultiplier} from '../src/progression.js';
test('old and invalid menus stay usable; unlocks charge once and choices trade speed for value',()=>{assert.deepEqual(migrateMenu(),{active:0,unlocked:[true,false,false]});assert.equal(migrateMenu({active:2,unlocked:[]}).active,0);const s={money:2500,productMenu:migrateMenu()};assert.equal(chooseFormat(s,2),false);assert.equal(chooseFormat(s,1),true);assert.equal(s.money,0);assert.equal(chooseFormat(s,0),true);assert.equal(chooseFormat(s,1),true);assert.equal(s.money,0);assert.equal(chooseFormat(s,9),false);assert.ok(FORMATS[1].packing>FORMATS[0].packing);assert.ok(FORMATS[1].service<FORMATS[0].service);assert.ok(FORMATS[2].demand<FORMATS[0].demand)});
test('milestones continue past city without non-finite costs or rewards',()=>{assert.equal(milestone(3).goal,250000);assert.equal(milestone(4).goal,1000000);for(let i=0;i<=20;i++){const m=milestone(i);assert.ok(Number.isSafeInteger(m.goal));assert.ok(m.reward<m.goal)}assert.equal(milestone(21),null);assert.ok(boostCost(BOOST_MAX-1)<250*4**(BOOST_MAX-1));assert.ok(Number.isSafeInteger(boostCost(500)))});
test('prestige is gated on lifetime revenue, safely migrates and multiplies base sales',()=>{const s={money:0,lifetime:9999999,empire:migrateProgression({prestige:0})};assert.equal(prestigeOffer(s).eligible,false);s.lifetime++;assert.equal(prestigeOffer(s).eligible,true);s.empire.prestige=1;assert.equal(prestigeOffer(s).eligible,false);assert.equal(saleMultiplier(s.empire),1.2);assert.equal(migrateProgression({prestige:Infinity}).prestige,0);assert.equal(migrateProgression({prestige:999}).prestige,19)});
test('VIP reward requires reputation unlock and a fast handoff',()=>{assert.equal(customerType(60,6),'vip');assert.notEqual(customerType(59,6),'vip');const p=migrateProgression({reputation:70});assert.equal(satisfyCustomer(p,-1,'vip','everyday',15),2);assert.equal(satisfyCustomer(p,-1,'vip','everyday',16),1)});
test('delayed timers preserve fixed steps, cap long-stall estimates and respect pause',()=>{assert.deepEqual(elapsedSteps(.2,4),{steps:16,offline:0});assert.deepEqual(elapsedSteps(.2,0),{steps:0,offline:0});assert.deepEqual(elapsedSteps(100000,1),{steps:0,offline:14400});assert.equal(elapsedSteps(-1,1).steps,0);assert.equal(elapsedSteps(NaN,1).steps,0);assert.equal(migrateProgression({returnReport:{seconds:86400,earnings:[1,2,3,4]}}).returnReport.seconds,86400)});
