(function () {
  'use strict';

  var LINES=[
    {name:'ORE CRUSHER',base:10,rate:1,unlock:0},{name:'SMELTER',base:100,rate:8,unlock:25},
    {name:'PARTS PRESS',base:850,rate:50,unlock:250},{name:'PACKING UNIT',base:6500,rate:280,unlock:2500}
  ];
  var ORDERS=[{name:'FIRST BATCH',goal:100,reward:40},{name:'STEADY SUPPLY',goal:1500,reward:450},{name:'MASS MARKET',goal:20000,reward:6000},{name:'CITY CONTRACT',goal:250000,reward:90000}];
  var $=function(id){return document.getElementById(id)};
  function fresh(){return{money:0,lifetime:0,lines:[0,0,0,0],multiplier:1,globalLevel:0,contract:0,lastSeen:Date.now()}}
  function load(){try{var old=JSON.parse(localStorage.getItem('shift-save')||'{}');return Object.assign(fresh(),old,{lines:Array.isArray(old.lines)?old.lines:[0,0,0,0]})}catch(e){return fresh()}}
  var state=load(),selected=0,toastTimer;
  function save(){state.lastSeen=Date.now();localStorage.setItem('shift-save',JSON.stringify(state))}
  function fmt(n){if(n<1000)return '$'+Math.floor(n).toLocaleString();var units=[['T',1e12],['B',1e9],['M',1e6],['K',1e3]];for(var i=0;i<units.length;i++)if(n>=units[i][1])return '$'+(n/units[i][1]).toFixed(n/units[i][1]>=100?0:n/units[i][1]>=10?1:2)+units[i][0]}
  function production(){return LINES.reduce(function(sum,line,i){return sum+line.rate*state.lines[i]},0)*state.multiplier}
  function cost(i){return Math.floor(LINES[i].base*Math.pow(1.16,state.lines[i]))}
  function tapValue(){return Math.max(1,Math.floor(1+production()*.08))}
  function add(n){state.money+=n;state.lifetime+=n}
  function notify(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){$('toast').classList.remove('show')},1600)}

  var world=$('world'),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  if(!ctx){$('loadStatus').textContent='CANVAS COULD NOT START';$('loadRetry').hidden=false;return}
  world.insertBefore(canvas,world.firstChild);canvas.setAttribute('aria-hidden','true');
  var dpr=1,width=1,height=1,angle=.78,zoom=1,centerX=0,centerY=0,unit=32;
  var colors={bg:'#11130f',floorTop:'#292c25',floorLeft:'#1c1f1a',floorRight:'#22251f',grid:'#3a3e34',beltEdge:'#11130e',belt:'#31342d',slat:'#5d6258',oliveTop:'#626c3a',oliveLeft:'#3b4325',oliveRight:'#4b542d',darkTop:'#34382f',darkLeft:'#20231d',darkRight:'#292c25',metalTop:'#8c9188',metalLeft:'#555a53',metalRight:'#6b7068',acid:'#d7ff43',orange:'#ff7628',boxTop:'#d3a36c',boxLeft:'#8e6741',boxRight:'#b17f50'};
  var machinePos=[{x:-5,z:-3.2},{x:0,z:-3.2},{x:5.2,z:.2},{x:-2.2,z:3.2}];
  var beltNodes=[[-5,-3.2],[0,-3.2],[5,-3.2],[5.4,0],[5,3.2],[0,3.2],[-5,3.2],[-5.4,0]];
  var crateTime=0,particles=[];

  function resize(){var rect=world.getBoundingClientRect();dpr=Math.min(window.devicePixelRatio||1,2);width=Math.max(1,Math.round(rect.width));height=Math.max(1,Math.round(rect.height));canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);centerX=width*.5;centerY=height*(width<780?.54:.53);unit=Math.min(width/18,height/12)*zoom}
  function rotate(x,z){var c=Math.cos(angle),s=Math.sin(angle);return{x:x*c-z*s,z:x*s+z*c}}
  function project(x,y,z){var r=rotate(x,z);return{x:centerX+r.x*unit,y:centerY+r.z*unit*.5-y*unit,depth:r.z}}
  function poly(points,fill,stroke){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(var i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
  function drawBox(x,z,y,w,d,h,palette){var p=palette||[colors.oliveTop,colors.oliveLeft,colors.oliveRight],b0=project(x-w/2,y,z-d/2),b1=project(x+w/2,y,z-d/2),b2=project(x+w/2,y,z+d/2),b3=project(x-w/2,y,z+d/2),t0=project(x-w/2,y+h,z-d/2),t1=project(x+w/2,y+h,z-d/2),t2=project(x+w/2,y+h,z+d/2),t3=project(x-w/2,y+h,z+d/2);poly([b3,b2,t2,t3],p[1]);poly([b2,b1,t1,t2],p[2]);poly([t0,t1,t2,t3],p[0],'#ffffff12')}
  function ellipse(x,y,rx,ry,fill){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill()}
  function beltPoint(t){t=(t%1+1)%1;var scaled=t*beltNodes.length,i=Math.floor(scaled),f=scaled-i,a=beltNodes[i%beltNodes.length],b=beltNodes[(i+1)%beltNodes.length];return{x:a[0]+(b[0]-a[0])*f,z:a[1]+(b[1]-a[1])*f}}
  function drawFloor(){ctx.fillStyle=colors.bg;ctx.fillRect(0,0,width,height);var floorPalette=[colors.floorTop,colors.floorLeft,colors.floorRight];drawBox(0,0,-.55,19,15,.55,floorPalette);ctx.strokeStyle=colors.grid;ctx.lineWidth=1;ctx.globalAlpha=.6;for(var x=-9;x<=9;x+=2){var a=project(x,.01,-7.4),b=project(x,.01,7.4);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(var z=-7;z<=7;z+=2){var c=project(-9.4,.01,z),d=project(9.4,.01,z);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke()}ctx.globalAlpha=1}
  function drawBelt(){var pts=[];for(var i=0;i<=96;i++){var p=beltPoint(i/96),s=project(p.x,.25,p.z);pts.push(s)}ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle=colors.beltEdge;ctx.lineWidth=unit*1.55;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.stroke();ctx.strokeStyle=colors.belt;ctx.lineWidth=unit*1.15;ctx.stroke();ctx.strokeStyle=colors.slat;ctx.lineWidth=Math.max(1,unit*.07);for(i=0;i<48;i++){var t=i/48,p1=beltPoint(t),p2=beltPoint(t+.003),sp1=project(p1.x,.27,p1.z),sp2=project(p2.x,.27,p2.z),dx=sp2.x-sp1.x,dy=sp2.y-sp1.y,len=Math.hypot(dx,dy)||1,nx=-dy/len*unit*.45,ny=dx/len*unit*.45;ctx.beginPath();ctx.moveTo(sp1.x-nx,sp1.y-ny);ctx.lineTo(sp1.x+nx,sp1.y+ny);ctx.stroke()}}
  function selectionRing(pos){var p=project(pos.x,.04,pos.z),rx=unit*1.7,ry=unit*.82;ctx.beginPath();ctx.ellipse(p.x,p.y,rx,ry,0,0,Math.PI*2);ctx.strokeStyle=colors.acid;ctx.lineWidth=2;ctx.setLineDash([6,5]);ctx.stroke();ctx.setLineDash([])}
  function drawCrusher(pos,time){drawBox(pos.x,pos.z,.02,2.6,2.4,.55,[colors.darkTop,colors.darkLeft,colors.darkRight]);drawBox(pos.x,pos.z,.57,1.9,1.7,1.25,[colors.oliveTop,colors.oliveLeft,colors.oliveRight]);drawBox(pos.x,pos.z,1.82,2.3,2.0,.5,[colors.metalTop,colors.metalLeft,colors.metalRight]);var gap=state.lines[0]?Math.sin(time*.01)*.16:0;drawBox(pos.x-.48+gap,pos.z,1.08,.72,.9,.55,[colors.metalTop,colors.metalLeft,colors.metalRight]);drawBox(pos.x+.48-gap,pos.z,1.08,.72,.9,.55,[colors.metalTop,colors.metalLeft,colors.metalRight]);drawLight(pos.x,pos.z+1.23,.76,state.lines[0]>0)}
  function drawSmelter(pos,time){drawBox(pos.x,pos.z,.02,2.7,2.4,.55,[colors.darkTop,colors.darkLeft,colors.darkRight]);drawBox(pos.x,pos.z,.57,2.15,1.9,2.2,[colors.oliveTop,colors.oliveLeft,colors.oliveRight]);drawBox(pos.x,pos.z+1,1.1,1.05,.16,.9,[colors.orange,'#9c330e','#c64b17']);drawBox(pos.x,pos.z,2.77,.75,.75,.85,[colors.darkTop,colors.darkLeft,colors.darkRight]);if(state.lines[1]){var p=project(pos.x,1.55,pos.z+1.12);ellipse(p.x,p.y,unit*(.34+Math.sin(time*.008)*.04),unit*.17,'#ff9b37')}}
  function drawPress(pos,time){drawBox(pos.x,pos.z,.02,2.7,2.5,.55,[colors.darkTop,colors.darkLeft,colors.darkRight]);drawBox(pos.x-.9,pos.z,.57,.32,1.4,2.7,[colors.metalTop,colors.metalLeft,colors.metalRight]);drawBox(pos.x+.9,pos.z,.57,.32,1.4,2.7,[colors.metalTop,colors.metalLeft,colors.metalRight]);drawBox(pos.x,pos.z,3.27,2.45,1.45,.65,[colors.oliveTop,colors.oliveLeft,colors.oliveRight]);var drop=state.lines[2]?(Math.sin(time*.008)+1)*.33:.22;drawBox(pos.x,pos.z,1.1+drop,1.15,1.05,.62,[colors.metalTop,colors.metalLeft,colors.metalRight]);drawLight(pos.x,pos.z+.74,3.4,state.lines[2]>0)}
  function drawPacker(pos,time){drawBox(pos.x,pos.z,.02,2.8,2.4,.55,[colors.darkTop,colors.darkLeft,colors.darkRight]);drawBox(pos.x-1,pos.z,.57,.35,1.4,2.5,[colors.metalTop,colors.metalLeft,colors.metalRight]);drawBox(pos.x+1,pos.z,.57,.35,1.4,2.5,[colors.metalTop,colors.metalLeft,colors.metalRight]);drawBox(pos.x,pos.z,3.07,2.35,1.35,.55,[colors.oliveTop,colors.oliveLeft,colors.oliveRight]);drawBox(pos.x,pos.z,1.35,1.5,.65,.72,[colors.orange,'#9c330e','#c64b17']);drawLight(pos.x,pos.z+.7,3.18,state.lines[3]>0)}
  function drawLight(x,z,y,on){var p=project(x,y,z);ellipse(p.x,p.y,Math.max(3,unit*.12),Math.max(2,unit*.065),on?colors.acid:'#272a23');if(on){ctx.strokeStyle='#d7ff4388';ctx.lineWidth=unit*.12;ctx.stroke()}}
  function drawCrate(t){var pos=beltPoint(t);drawBox(pos.x,pos.z,.82,.72,.72,.72,[colors.boxTop,colors.boxLeft,colors.boxRight]);return pos}
  function depthOf(pos){return rotate(pos.x,pos.z).z}
  function render(now){drawFloor();drawBelt();if(selected>=0)selectionRing(machinePos[selected]);var jobs=machinePos.map(function(pos,i){return{depth:depthOf(pos),draw:function(){[drawCrusher,drawSmelter,drawPress,drawPacker][i](pos,now)}}});var crateCount=Math.min(12,state.lines.reduce(function(a,b){return a+b},0));var speed=production()>0?Math.min(.09,.018+production()*.00003):0;crateTime=(crateTime+(now-(render.last||now))/1000*speed)%1;render.last=now;for(var i=0;i<crateCount;i++){(function(t){var pos=beltPoint(t);jobs.push({depth:depthOf(pos),draw:function(){drawCrate(t)}})}((crateTime+i/Math.max(1,crateCount))%1))}jobs.sort(function(a,b){return a.depth-b.depth});jobs.forEach(function(job){job.draw()});for(i=particles.length-1;i>=0;i--){var part=particles[i];part.life-=.025;part.x+=part.vx;part.y+=part.vy;part.vy+=.08;ctx.globalAlpha=Math.max(0,part.life);ctx.fillStyle=part.color;ctx.fillRect(part.x,part.y,5,5);ctx.globalAlpha=1;if(part.life<=0)particles.splice(i,1)}updateMarkers();requestAnimationFrame(render)}
  function burst(worldPos,color){var p=project(worldPos.x,1.4,worldPos.z);for(var i=0;i<12;i++)particles.push({x:p.x,y:p.y,vx:(Math.random()-.5)*4,vy:-Math.random()*4-1,life:1,color:color||colors.acid})}

  var markerEls=LINES.map(function(line,i){var b=document.createElement('button');b.className='marker';b.textContent=line.name;b.onclick=function(){selectMachine(i)};$('markers').appendChild(b);return b});
  function updateMarkers(){markerEls.forEach(function(el,i){var pos=project(machinePos[i].x,3.8,machinePos[i].z);el.style.left=pos.x+'px';el.style.top=pos.y+'px';el.style.display=pos.x<-80||pos.x>width+80||pos.y<-40||pos.y>height+40?'none':'block'})}
  function renderUI(){var line=LINES[selected],open=state.lifetime>=line.unlock,level=state.lines[selected];$('money').textContent=fmt(state.money);$('rate').textContent=fmt(production())+'/s';$('tapValue').textContent='+'+fmt(tapValue());$('machineNumber').textContent=open?'MACHINE 0'+(selected+1):'UNLOCK AT '+fmt(line.unlock);$('machineName').textContent=line.name;$('machineLevel').textContent=level;$('machineRate').textContent=fmt(line.rate*level*state.multiplier)+'/s';$('machineCost').textContent=fmt(cost(selected));$('buyMachine').disabled=!open;$('buyMachine').querySelector('span').textContent=level?'UPGRADE':'BUILD';var order=ORDERS[state.contract];if(order){$('orderName').textContent=order.name;$('orderProgress').textContent=fmt(Math.min(state.lifetime,order.goal))+' / '+fmt(order.goal);$('orderFill').style.width=Math.min(100,state.lifetime/order.goal*100)+'%';$('claimReward').textContent='+'+fmt(order.reward);$('claim').disabled=state.lifetime<order.goal}else{$('orderName').textContent='ALL ORDERS FILLED';$('orderProgress').textContent='COMPLETE';$('orderFill').style.width='100%';$('claimReward').textContent='✓';$('claim').disabled=true}$('boostCost').textContent=fmt(Math.floor(250*Math.pow(4,state.globalLevel)));markerEls.forEach(function(el,i){el.classList.toggle('selected',i===selected);el.classList.toggle('locked',state.lifetime<LINES[i].unlock);el.textContent=state.lifetime<LINES[i].unlock?fmt(LINES[i].unlock):LINES[i].name})}
  function selectMachine(i){selected=i;renderUI();if(navigator.vibrate)navigator.vibrate(8)}
  function buySelected(){var line=LINES[selected];if(state.lifetime<line.unlock)return notify('Unlocks at '+fmt(line.unlock));var c=cost(selected);if(state.money<c)return notify('Need '+fmt(c-state.money)+' more');state.money-=c;state.lines[selected]++;burst(machinePos[selected]);notify(line.name+' · LEVEL '+state.lines[selected]);renderUI();save();if(navigator.vibrate)navigator.vibrate(18)}
  function runManual(){var value=tapValue();add(value);burst({x:0,z:0});var f=document.createElement('span');f.className='float';f.textContent='+'+fmt(value);$('floatLayer').appendChild(f);setTimeout(function(){f.remove()},800);renderUI();save();if(navigator.vibrate)navigator.vibrate(10)}
  function boostAll(){var c=Math.floor(250*Math.pow(4,state.globalLevel));if(state.money<c)return notify('Need '+fmt(c-state.money)+' more');state.money-=c;state.globalLevel++;state.multiplier=Math.pow(1.25,state.globalLevel);burst({x:0,z:0},colors.orange);notify('ALL MACHINES +25%');renderUI();save()}
  function claimOrder(){var o=ORDERS[state.contract];if(!o||state.lifetime<o.goal)return;state.money+=o.reward;state.contract++;notify(fmt(o.reward)+' ORDER BONUS');renderUI();save()}

  var pointers={},dragStart=null,lastX=0,pinchDistance=0;
  canvas.addEventListener('pointerdown',function(e){canvas.setPointerCapture(e.pointerId);pointers[e.pointerId]={x:e.clientX,y:e.clientY};if(Object.keys(pointers).length===1){dragStart={x:e.clientX,y:e.clientY};lastX=e.clientX}else{var ps=Object.values(pointers);pinchDistance=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)}});
  canvas.addEventListener('pointermove',function(e){if(!pointers[e.pointerId])return;pointers[e.pointerId]={x:e.clientX,y:e.clientY};var ps=Object.values(pointers);if(ps.length===1){angle-=(e.clientX-lastX)*.006;lastX=e.clientX}else if(ps.length===2){var dist=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);if(pinchDistance){zoom=Math.max(.72,Math.min(1.5,zoom+(dist-pinchDistance)*.003));resize()}pinchDistance=dist}});
  canvas.addEventListener('pointerup',function(e){var moved=dragStart?Math.hypot(e.clientX-dragStart.x,e.clientY-dragStart.y):99;if(moved<8&&Object.keys(pointers).length===1){var best=-1,bestDist=68;machinePos.forEach(function(pos,i){var p=project(pos.x,1.4,pos.z),dist=Math.hypot(e.clientX-p.x,e.clientY-p.y);if(dist<bestDist){best=i;bestDist=dist}});if(best>=0)selectMachine(best)}delete pointers[e.pointerId];dragStart=null;pinchDistance=0});
  canvas.addEventListener('wheel',function(e){e.preventDefault();zoom=Math.max(.72,Math.min(1.5,zoom-e.deltaY*.001));resize()},{passive:false});
  window.addEventListener('resize',resize);$('buyMachine').onclick=buySelected;$('run').onclick=runManual;$('boost').onclick=boostAll;$('claim').onclick=claimOrder;$('resetOpen').onclick=function(){$('resetModal').hidden=false};$('resetCancel').onclick=function(){$('resetModal').hidden=true};$('resetConfirm').onclick=function(){state=fresh();save();$('resetModal').hidden=true;notify('FACTORY RESET');renderUI()};

  function playLoadSequence(){var steps=Array.prototype.slice.call(document.querySelectorAll('[data-load-step]')),bar=$('loadBar'),percent=$('loadPercent'),status=$('loadStatus'),i=0;function advance(){if(i>0){steps[i-1].classList.remove('active');steps[i-1].classList.add('done');steps[i-1].querySelector('i').textContent='READY'}if(i===steps.length){bar.style.width='100%';percent.textContent='100%';status.textContent='PRODUCTION ONLINE';setTimeout(function(){$('loading').classList.add('done')},220);return}steps[i].classList.add('active');steps[i].querySelector('i').textContent='BUILDING';var value=Math.round((i+1)/steps.length*100);bar.style.width=value+'%';percent.textContent=value+'%';status.textContent=steps[i].querySelector('b').textContent.toUpperCase();i++;setTimeout(advance,150)}advance()}
  var away=Math.min(14400,(Date.now()-state.lastSeen)/1000),offline=production()*away;if(offline>=1){add(offline);setTimeout(function(){notify('WHILE AWAY +'+fmt(offline))},500)}
  resize();renderUI();ctx.fillStyle=colors.bg;ctx.fillRect(0,0,width,height);window.__shiftReady=true;playLoadSequence();requestAnimationFrame(render);setTimeout(function(){$('gestureHint').style.opacity=.25},5000);setInterval(function(){add(production()/4);renderUI()},250);setInterval(save,5000);window.addEventListener('beforeunload',save);

  if(document.modelContext&&document.modelContext.registerTool){document.modelContext.registerTool({name:'read_factory_status',title:'Read factory status',description:'Read cash, production, and machine levels.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:function(){return{cash:Math.floor(state.money),lifetime:Math.floor(state.lifetime),perSecond:production(),lineLevels:state.lines}}});document.modelContext.registerTool({name:'run_factory_machine',title:'Run factory machine',description:'Run the factory once.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:function(){var value=tapValue();add(value);renderUI();save();return{produced:value,cash:Math.floor(state.money)}}})}
})();
