import * as THREE from 'three';
import './style.css';

const LINES=[
  {name:'ORE CRUSHER',base:10,rate:1,unlock:0},{name:'SMELTER',base:100,rate:8,unlock:25},
  {name:'PARTS PRESS',base:850,rate:50,unlock:250},{name:'PACKING UNIT',base:6500,rate:280,unlock:2500}
];
const ORDERS=[{name:'FIRST BATCH',goal:100,reward:40},{name:'STEADY SUPPLY',goal:1500,reward:450},{name:'MASS MARKET',goal:20000,reward:6000},{name:'CITY CONTRACT',goal:250000,reward:90000}];
const fresh=()=>({money:0,lifetime:0,lines:[0,0,0,0],multiplier:1,globalLevel:0,contract:0,lastSeen:Date.now()});
const $=id=>document.getElementById(id);let state=load(),selected=0,toastTimer;
function load(){try{const old=JSON.parse(localStorage.getItem('shift-save')||'{}');return {...fresh(),...old,lines:Array.isArray(old.lines)?old.lines:[0,0,0,0]}}catch{return fresh()}}
function save(){state.lastSeen=Date.now();localStorage.setItem('shift-save',JSON.stringify(state))}
function fmt(n){if(n<1000)return '$'+Math.floor(n).toLocaleString();for(const [s,v] of [['T',1e12],['B',1e9],['M',1e6],['K',1e3]])if(n>=v)return '$'+(n/v).toFixed(n/v>=100?0:n/v>=10?1:2)+s}
function production(){return LINES.reduce((sum,l,i)=>sum+l.rate*state.lines[i],0)*state.multiplier}
function cost(i){return Math.floor(LINES[i].base*Math.pow(1.16,state.lines[i]))}
function tapValue(){return Math.max(1,Math.floor(1+production()*.08))}
function add(n){state.money+=n;state.lifetime+=n}
function notify(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1600)}

const world=$('world');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x11130f);scene.fog=new THREE.Fog(0x11130f,20,38);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{world.innerHTML='<div class="loading">3D graphics are not available on this device.</div>';throw new Error('WebGL unavailable')}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;world.prepend(renderer.domElement);
const camera=new THREE.OrthographicCamera(-10,10,10,-10,.1,100);const target=new THREE.Vector3(0,0,0);let cameraAngle=.78,cameraZoom=1;
const ambient=new THREE.HemisphereLight(0xdce9c0,0x24261f,2.1);scene.add(ambient);const sun=new THREE.DirectionalLight(0xffe6bb,3.4);sun.position.set(-7,15,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;scene.add(sun);

const MAT={floor:new THREE.MeshStandardMaterial({color:0x262922,roughness:.88}),edge:new THREE.MeshStandardMaterial({color:0x383c31,roughness:.7}),belt:new THREE.MeshStandardMaterial({color:0x242621,roughness:.75}),olive:new THREE.MeshStandardMaterial({color:0x525c2f,roughness:.65,metalness:.22}),oliveDark:new THREE.MeshStandardMaterial({color:0x30361f,roughness:.7,metalness:.15}),metal:new THREE.MeshStandardMaterial({color:0x71756d,roughness:.42,metalness:.75}),dark:new THREE.MeshStandardMaterial({color:0x171914,roughness:.7}),orange:new THREE.MeshStandardMaterial({color:0xff7628,roughness:.5,emissive:0x6b1f00,emissiveIntensity:.35}),lime:new THREE.MeshStandardMaterial({color:0xd7ff43,emissive:0x8fb800,emissiveIntensity:1.6}),box:new THREE.MeshStandardMaterial({color:0xc5955d,roughness:.9})};
function mesh(geo,mat,x=0,y=0,z=0){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m}
function box(x,y,z,mat=MAT.olive,px=0,py=0,pz=0){return mesh(new THREE.BoxGeometry(x,y,z),mat,px,py,pz)}
function tag(group,index){group.userData.machineIndex=index;group.traverse(o=>o.userData.machineIndex=index);const ring=mesh(new THREE.RingGeometry(1.45,1.55,32),new THREE.MeshBasicMaterial({color:0xd7ff43,transparent:true,opacity:.85,side:THREE.DoubleSide}),0,.04,0);ring.rotation.x=-Math.PI/2;ring.visible=false;ring.userData.machineIndex=index;group.add(ring);group.userData.ring=ring;return group}

const base=box(19,.6,15,MAT.floor,0,-.45,0);scene.add(base);const edge=box(19.25,.22,15.25,MAT.edge,0,-.08,0);scene.add(edge);
const tileMat=new THREE.LineBasicMaterial({color:0x3b3e35,transparent:true,opacity:.45});const tilePts=[];for(let x=-9;x<=9;x+=2){tilePts.push(new THREE.Vector3(x,-.05,-7.4),new THREE.Vector3(x,-.05,7.4))}for(let z=-7;z<=7;z+=2){tilePts.push(new THREE.Vector3(-9.4,-.05,z),new THREE.Vector3(9.4,-.05,z))}scene.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(tilePts),tileMat));

const path=new THREE.CatmullRomCurve3([new THREE.Vector3(-5,.35,-3.2),new THREE.Vector3(0,.35,-3.2),new THREE.Vector3(5,.35,-3.2),new THREE.Vector3(5.4,.35,0),new THREE.Vector3(5,.35,3.2),new THREE.Vector3(0,.35,3.2),new THREE.Vector3(-5,.35,3.2),new THREE.Vector3(-5.4,.35,0)],true,'centripetal');
const belt=mesh(new THREE.TubeGeometry(path,120,.68,4,true),MAT.belt);belt.receiveShadow=true;scene.add(belt);
for(let i=0;i<48;i++){const t=i/48,p=path.getPointAt(t),tan=path.getTangentAt(t),slat=box(.17,.09,1.18,MAT.metal,p.x,p.y+.5,p.z);slat.rotation.y=Math.atan2(tan.x,tan.z);scene.add(slat)}

const machines=[],parts=[];
function crusher(){const g=new THREE.Group();g.position.set(-5,0,-3.2);const base=box(2.5,.55,2.5,MAT.oliveDark,0,.3,0);g.add(base);const legs=[[-.8,.9,-.7],[.8,.9,-.7],[-.8,.9,.7],[.8,.9,.7]];legs.forEach(p=>g.add(box(.3,1.25,.3,MAT.metal,...p)));const hopper=mesh(new THREE.CylinderGeometry(.72,1.22,1.5,4),MAT.olive,0,2,0);hopper.rotation.y=Math.PI/4;g.add(hopper);const jaw1=box(.85,.5,.85,MAT.metal,-.48,1.05,0),jaw2=box(.85,.5,.85,MAT.metal,.48,1.05,0);g.add(jaw1,jaw2);const light=box(.3,.18,.12,MAT.lime,0,.72,1.27);g.add(light);parts[0]={jaw1,jaw2,light};return tag(g,0)}
function smelter(){const g=new THREE.Group();g.position.set(0,0,-3.2);g.add(box(2.7,.55,2.4,MAT.oliveDark,0,.3,0));const tower=mesh(new THREE.CylinderGeometry(1.05,1.25,2.45,8),MAT.olive,0,1.7,0);g.add(tower);const rim=mesh(new THREE.TorusGeometry(1.12,.14,8,24),MAT.metal,0,1.5,0);rim.rotation.x=Math.PI/2;g.add(rim);const door=box(1.05,.85,.12,MAT.orange,0,1.35,1.08);g.add(door);const chimney=mesh(new THREE.CylinderGeometry(.35,.45,.9,8),MAT.dark,0,3.35,0);g.add(chimney);parts[1]={tower,door};return tag(g,1)}
function press(){const g=new THREE.Group();g.position.set(5.25,0,.2);g.add(box(2.7,.55,2.5,MAT.oliveDark,0,.3,0));[-.9,.9].forEach(x=>g.add(box(.3,2.7,.35,MAT.metal,x,1.75,0)));const top=box(2.45,.65,1.35,MAT.olive,0,3,0);g.add(top);const head=box(1.1,.55,1.05,MAT.metal,0,1.7,0);g.add(head);const piston=mesh(new THREE.CylinderGeometry(.2,.2,1.3,10),MAT.metal,0,2.35,0);g.add(piston);const light=box(.55,.18,.13,MAT.lime,0,3.08,.7);g.add(light);parts[2]={head,piston,light};return tag(g,2)}
function packer(){const g=new THREE.Group();g.position.set(-2.2,0,3.2);g.add(box(2.8,.55,2.4,MAT.oliveDark,0,.3,0));g.add(box(.35,2.5,.35,MAT.metal,-1,1.65,0),box(.35,2.5,.35,MAT.metal,1,1.65,0),box(2.35,.5,1.2,MAT.olive,0,2.85,0));const roller=mesh(new THREE.CylinderGeometry(.48,.48,1.5,12),MAT.orange,0,1.65,0);roller.rotation.z=Math.PI/2;g.add(roller);const light=box(.55,.16,.12,MAT.lime,0,2.88,.66);g.add(light);parts[3]={roller,light};return tag(g,3)}
[crusher(),smelter(),press(),packer()].forEach(m=>{machines.push(m);scene.add(m)});

const crateGeo=new THREE.BoxGeometry(.72,.72,.72),crates=[];function syncCrates(){const wanted=Math.min(12,state.lines.reduce((a,b)=>a+b,0));while(crates.length<wanted){const c=mesh(crateGeo,MAT.box);c.userData.crate=true;scene.add(c);crates.push(c)}while(crates.length>wanted){scene.remove(crates.pop())}}
const markerEls=LINES.map((line,i)=>{const b=document.createElement('button');b.className='marker';b.textContent=line.name;b.onclick=()=>selectMachine(i);$('markers').append(b);return b});

function renderUI(){const line=LINES[selected],open=state.lifetime>=line.unlock,level=state.lines[selected];$('money').textContent=fmt(state.money);$('rate').textContent=fmt(production())+'/s';$('tapValue').textContent='+'+fmt(tapValue());$('machineNumber').textContent=open?`MACHINE 0${selected+1}`:`UNLOCK AT ${fmt(line.unlock)}`;$('machineName').textContent=line.name;$('machineLevel').textContent=level;$('machineRate').textContent=fmt(line.rate*level*state.multiplier)+'/s';$('machineCost').textContent=fmt(cost(selected));$('buyMachine').disabled=!open;$('buyMachine').querySelector('span').textContent=level?'UPGRADE':'BUILD';const order=ORDERS[state.contract];if(order){$('orderName').textContent=order.name;$('orderProgress').textContent=`${fmt(Math.min(state.lifetime,order.goal))} / ${fmt(order.goal)}`;$('orderFill').style.width=Math.min(100,state.lifetime/order.goal*100)+'%';$('claimReward').textContent='+'+fmt(order.reward);$('claim').disabled=state.lifetime<order.goal}else{$('orderName').textContent='ALL ORDERS FILLED';$('orderProgress').textContent='COMPLETE';$('orderFill').style.width='100%';$('claimReward').textContent='✓';$('claim').disabled=true}$('boostCost').textContent=fmt(Math.floor(250*Math.pow(4,state.globalLevel)));markerEls.forEach((el,i)=>{el.classList.toggle('selected',i===selected);el.classList.toggle('locked',state.lifetime<LINES[i].unlock);el.textContent=state.lifetime<LINES[i].unlock?fmt(LINES[i].unlock):LINES[i].name});machines.forEach((m,i)=>{m.userData.ring.visible=i===selected;const active=state.lines[i]>0;parts[i].light.material=active?MAT.lime:MAT.dark});syncCrates()}
function selectMachine(i){selected=i;renderUI();navigator.vibrate?.(8)}
function buySelected(){const line=LINES[selected];if(state.lifetime<line.unlock)return notify(`Unlocks at ${fmt(line.unlock)}`);const c=cost(selected);if(state.money<c)return notify(`Need ${fmt(c-state.money)} more`);state.money-=c;state.lines[selected]++;burst(machines[selected].position,0xd7ff43);notify(`${line.name} · LEVEL ${state.lines[selected]}`);renderUI();save();navigator.vibrate?.(18)}
function runManual(){const value=tapValue();add(value);burst(new THREE.Vector3(0,.4,0),0xd7ff43);const f=document.createElement('span');f.className='float';f.textContent='+'+fmt(value);$('floatLayer').append(f);setTimeout(()=>f.remove(),800);renderUI();save();navigator.vibrate?.(10)}
function boostAll(){const c=Math.floor(250*Math.pow(4,state.globalLevel));if(state.money<c)return notify(`Need ${fmt(c-state.money)} more`);state.money-=c;state.globalLevel++;state.multiplier=Math.pow(1.25,state.globalLevel);burst(new THREE.Vector3(0,.6,0),0xff7628,20);notify('ALL MACHINES +25%');renderUI();save()}
function claimOrder(){const o=ORDERS[state.contract];if(!o||state.lifetime<o.goal)return;state.money+=o.reward;state.contract++;notify(`${fmt(o.reward)} ORDER BONUS`);renderUI();save()}

const particles=[];function burst(position,color,count=10){for(let i=0;i<count;i++){const p=mesh(new THREE.BoxGeometry(.1,.1,.1),new THREE.MeshBasicMaterial({color}),position.x,position.y+1,position.z);p.userData.velocity=new THREE.Vector3((Math.random()-.5)*.12,Math.random()*.12+.06,(Math.random()-.5)*.12);p.userData.life=1;scene.add(p);particles.push(p)}}

function resize(){const w=world.clientWidth,h=world.clientHeight,aspect=w/h,view=window.innerWidth<780?13:15;camera.left=-view*aspect/2;camera.right=view*aspect/2;camera.top=view/2;camera.bottom=-view/2;camera.updateProjectionMatrix();renderer.setSize(w,h,false);updateCamera()}
function updateCamera(){const dist=18;camera.position.set(Math.cos(cameraAngle)*dist,11,Math.sin(cameraAngle)*dist);camera.zoom=cameraZoom;camera.updateProjectionMatrix();camera.lookAt(target)}
window.addEventListener('resize',resize);resize();

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),activePointers=new Map();let dragStart=null,lastPoint=null,lastPinch=0;
function raycast(clientX,clientY){const rect=renderer.domElement.getBoundingClientRect();pointer.x=((clientX-rect.left)/rect.width)*2-1;pointer.y=-((clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects([...machines,...crates],true);if(!hits.length)return;const hit=hits[0].object;if(hit.userData.crate){const bonus=tapValue()*5;add(bonus);burst(hit.position,0xff7628);notify(`RUSH CRATE +${fmt(bonus)}`);renderUI();return}const i=hit.userData.machineIndex;if(Number.isInteger(i))selectMachine(i)}
renderer.domElement.addEventListener('pointerdown',e=>{renderer.domElement.setPointerCapture(e.pointerId);activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(activePointers.size===1){dragStart={x:e.clientX,y:e.clientY};lastPoint={...dragStart}}else if(activePointers.size===2){const p=[...activePointers.values()];lastPinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}});
renderer.domElement.addEventListener('pointermove',e=>{if(!activePointers.has(e.pointerId))return;activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(activePointers.size===1&&lastPoint){cameraAngle-=(e.clientX-lastPoint.x)*.006;lastPoint={x:e.clientX,y:e.clientY};updateCamera()}else if(activePointers.size===2){const p=[...activePointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(lastPinch){cameraZoom=THREE.MathUtils.clamp(cameraZoom+(d-lastPinch)*.003,.72,1.55);updateCamera()}lastPinch=d}});
renderer.domElement.addEventListener('pointerup',e=>{const moved=dragStart?Math.hypot(e.clientX-dragStart.x,e.clientY-dragStart.y):99;if(moved<7&&activePointers.size===1)raycast(e.clientX,e.clientY);activePointers.delete(e.pointerId);lastPoint=null;dragStart=null;lastPinch=0});
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();cameraZoom=THREE.MathUtils.clamp(cameraZoom-e.deltaY*.001,.72,1.55);updateCamera()},{passive:false});

$('buyMachine').onclick=buySelected;$('run').onclick=runManual;$('boost').onclick=boostAll;$('claim').onclick=claimOrder;$('resetOpen').onclick=()=>$('resetModal').hidden=false;$('resetCancel').onclick=()=>$('resetModal').hidden=true;$('resetConfirm').onclick=()=>{state=fresh();save();$('resetModal').hidden=true;notify('FACTORY RESET');renderUI()};

const away=Math.min(14400,(Date.now()-state.lastSeen)/1000),offline=production()*away;if(offline>=1){add(offline);setTimeout(()=>notify(`WHILE AWAY +${fmt(offline)}`),500)}
let previous=performance.now(),beltTime=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min(.04,(now-previous)/1000);previous=now;const speed=production()>0?Math.min(.09,.018+production()*.00003):0;beltTime=(beltTime+dt*speed)%1;crates.forEach((c,i)=>{const t=(beltTime+i/Math.max(1,crates.length))%1,p=path.getPointAt(t),tan=path.getTangentAt(t);c.position.copy(p).add(new THREE.Vector3(0,.95,0));c.rotation.y=Math.atan2(tan.x,tan.z)});const active=state.lines.map(n=>n>0);if(active[0]){const s=Math.sin(now*.01)*.16;parts[0].jaw1.position.x=-.48+s;parts[0].jaw2.position.x=.48-s}if(active[1])parts[1].door.material.emissiveIntensity=1.1+Math.sin(now*.006)*.7;if(active[2])parts[2].head.position.y=1.72+Math.sin(now*.007)*.48;if(active[3])parts[3].roller.rotation.x+=dt*2.4;particles.forEach((p,i)=>{p.position.add(p.userData.velocity);p.userData.velocity.y-=.006;p.userData.life-=dt*1.8;p.scale.setScalar(Math.max(0,p.userData.life));if(p.userData.life<=0){scene.remove(p);particles.splice(i,1)}});machines.forEach((m,i)=>{const v=m.position.clone();v.y+=3.5;v.project(camera);markerEls[i].style.left=(v.x*.5+.5)*world.clientWidth+'px';markerEls[i].style.top=(-v.y*.5+.5)*world.clientHeight+'px';markerEls[i].style.display=v.z>1?'none':'block'});renderer.render(scene,camera)}
renderUI();animate(performance.now());setTimeout(()=>$('loading').classList.add('done'),350);setTimeout(()=>$('gestureHint').style.opacity=.25,5000);setInterval(()=>{add(production()/4);renderUI()},250);setInterval(save,5000);window.addEventListener('beforeunload',save);

if(document.modelContext?.registerTool){[{name:'read_factory_status',title:'Read factory status',description:'Read the current cash, production, selected machine, and machine levels.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({cash:Math.floor(state.money),lifetime:Math.floor(state.lifetime),perSecond:production(),selectedMachine:LINES[selected].name,lineLevels:state.lines})},{name:'run_factory_machine',title:'Run factory machine',description:'Run the factory once and add the manual production value.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{const value=tapValue();add(value);renderUI();save();return{produced:value,cash:Math.floor(state.money)}}}].forEach(tool=>document.modelContext.registerTool(tool))}
