import {BRANCH_NAMES,LINES,STAFF,REGULARS,COSMETICS,staffLevel,shelfCapacity,shelfUsed,allocateShelf,developProduct,chooseRecipe,customize,importHarvest,transferReason,sendTransfer,deliveryReason,dispatchDelivery,upgradeFleet,expandArea,openingStatus,claimOpening,storyStatus,fulfillStory,neighborhood} from './operations.js';
import {PRODUCTS,MANAGERS,exclusiveAvailable,setFeatured,assignManager} from './progression.js';
export function mountOperations({getState,format,changed,visit}){
 const $=id=>document.getElementById(id),selected=[0,0,0];
 const act=(fn,message)=>{const result=fn();if(result)changed(message);return result;};
 // Pills replace repetitive dropdowns for short option lists: one tap picks the value, no open/close step.
 const SWATCHES={counter:['#c2a073','#849596','#ede4ce'],awning:['#8fa787','#d5a08b','#e4deca'],lighting:['#ffe2aa','#c1e4f1','#ffc079']};
 const pillGroup=(id,label,options,values,swatchKey)=>{const vals=values||options.map((_,j)=>j),swatches=swatchKey&&SWATCHES[swatchKey];return '<div class="pill-field"><span class="pill-label">'+label+'</span><div class="pill-group" role="group" aria-label="'+label+'" id="'+id+'">'+options.map((opt,j)=>'<button type="button" data-value="'+vals[j]+'">'+(swatches?'<span class="pill-swatch" style="background:'+swatches[j]+'"></span>':'')+opt+'</button>').join('')+'</div></div>'};
 const setPill=(id,value)=>{$(id).querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===String(value))))};
 const pillValue=id=>{const b=$(id).querySelector('[aria-pressed=true]');return b?b.dataset.value:null};
 const pillButton=(id,value)=>$(id).querySelector('[data-value="'+value+'"]');
 const onPill=(id,handler)=>$(id).addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;handler(b.dataset.value)});
 function showTab(i,index){selected[i]=index;['overview','stock','people','style'].forEach((name,j)=>{$('opTab'+i+j).setAttribute('aria-pressed',String(j===index));$('opPane'+i+j).hidden=j!==index;});}
 BRANCH_NAMES.forEach((name,i)=>{
  const body=$('branchBody'+i),overview=document.createElement('div');overview.id='opPane'+i+'0';overview.className='op-pane';while(body.firstChild)overview.appendChild(body.firstChild);body.appendChild(overview);
  const nav=document.createElement('nav');nav.className='operation-tabs';nav.setAttribute('aria-label',name+' management');const tabIcons=['<path d="M4 10.5 12 4l8 6.5V20H4z M9 20v-6h6v6"/>','<path d="M4 8h16v11H4zM4 8l3-4h10l3 4M12 4v4"/>','<circle cx="9" cy="8" r="3"/><circle cx="16" cy="9" r="2.4"/><path d="M3 20a6 6 0 0 1 12 0M13 20a4.5 4.5 0 0 1 8 0"/>','<path d="M5 17c2 0 3-1 3-3l7-7 3 3-7 7c-2 0-3 1-3 3-2 0-3-1-3-3ZM14 6l3 3"/>'];nav.innerHTML=['Overview','Stock','People','Style'].map((t,j)=>'<button id="opTab'+i+j+'" aria-pressed="'+(j===0)+'"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+tabIcons[j]+'</svg><em>'+t+'</em></button>').join('');const header=document.createElement('div');header.className='branch-sticky-header';const toggle=$('branchToggle'+i);toggle.before(header);header.append(toggle,nav);nav.hidden=body.hidden;
  ['Stock','People','Style'].forEach((_,j)=>{const pane=document.createElement('div');pane.id='opPane'+i+(j+1);pane.className='op-pane';pane.hidden=true;body.appendChild(pane);});
  [0,1,2,3].forEach(j=>$('opTab'+i+j).onclick=()=>showTab(i,j));
  const opening=document.createElement('div');opening.className='opening-task';opening.innerHTML='<span id="openingLabel'+i+'"></span><button id="openingClaim'+i+'"></button><progress id="openingProgress'+i+'" max="100" aria-label="Grand-opening goal"></progress>';
  overview.prepend(opening);$('openingClaim'+i).onclick=()=>act(()=>claimOpening(getState(),i),'Grand-opening goal complete');
  $('opPane'+i+'1').innerHTML='<div class="operation-stats"><strong id="harvestCount'+i+'"></strong><span id="shelfCount'+i+'"></span></div>'+pillGroup('featured'+i,'Feature',PRODUCTS.map(f=>({everyday:'Everyday',exclusive:'River Mist',boutique:'Boutique',express:'Express'})[f]),PRODUCTS)+'<p id="featuredEffect'+i+'" class="choice-effect"></p>'+pillGroup('recipe'+i,'Make',LINES.map(l=>l.name),LINES.map((_,j)=>j))+'<p class="operation-hint" id="craftStatus'+i+'"></p><div class="shelf-list">'+LINES.map((l,j)=>'<div class="shelf-row"><div><strong>'+l.name+'</strong><small id="lineCount'+i+j+'"></small></div>'+(j?'<button id="research'+i+j+'" class="shelf-unlock"></button>':'')+'<div class="shelf-stepper" id="shelfStepper'+i+j+'"><button id="shelfLess'+i+j+'" aria-label="Remove five '+l.name+' shelf spaces">−</button><span id="shelfAllocation'+i+j+'"></span><button id="shelfMore'+i+j+'" aria-label="Add five '+l.name+' shelf spaces">+</button></div></div>').join('')+'</div><details class="operation-details"><summary>Transfers &amp; deliveries <span id="routeBadge'+i+'"></span></summary><div class="operation-row"><span>Riverside harvest</span><button id="importHarvest'+i+'">Import 10</button></div><p class="operation-hint">Vans run while playing · income continues offline.</p>'+pillGroup('transferTo'+i,'Send 10 harvest to',['Old Town','City Center','Desert Oasis','Alpine'],['1','2','3','4'])+'<button class="operation-primary" id="transferSend'+i+'">Send transfer</button><p id="transferReason'+i+'" class="operation-hint"></p>'+pillGroup('deliveryLine'+i,'Deliver 5',LINES.map(l=>l.name),LINES.map((_,j)=>j))+pillGroup('deliveryArea'+i,'Area',['Local','District','Citywide'])+pillGroup('walkinReserve'+i,'Keep for walk-ins',['0','5','10'])+'<button class="operation-primary" id="deliverySend'+i+'">Dispatch</button><p class="operation-hint" id="deliveryHint'+i+'"></p><div id="routes'+i+'" class="route-list"></div><div class="operation-row"><span id="fleetLabel'+i+'"></span><button id="fleetUpgrade'+i+'"></button></div><div class="operation-row"><span>Delivery coverage</span><button id="areaUpgrade'+i+'"></button></div></details>';
  onPill('recipe'+i,value=>act(()=>chooseRecipe(getState().empire,i,Number(value)),'Production line changed'));
  onPill('featured'+i,value=>act(()=>setFeatured(getState().empire,i,value),'Featured product changed'));
  LINES.forEach((l,j)=>{[-1,1].forEach(dir=>$('shelf'+(dir<0?'Less':'More')+i+j).onclick=()=>act(()=>allocateShelf(getState().empire,i,j,dir*5),'Shelf plan updated'));if(j)$('research'+i+j).onclick=()=>act(()=>developProduct(getState(),j),l.name+' developed');});
  setPill('transferTo'+i,i===2?'2':'1');setPill('deliveryLine'+i,'0');
  onPill('transferTo'+i,value=>setPill('transferTo'+i,value));
  onPill('deliveryLine'+i,value=>setPill('deliveryLine'+i,value));
  $('transferSend'+i).onclick=()=>act(()=>sendTransfer(getState().empire,Number(pillValue('transferTo'+i))),'Van dispatched from Riverside');
  $('importHarvest'+i).onclick=()=>act(()=>importHarvest(getState()),'10 harvest moved to Riverside');
  $('deliverySend'+i).onclick=()=>act(()=>dispatchDelivery(getState().empire,i,Number(pillValue('deliveryLine'+i))),'Driver dispatched');
  onPill('deliveryArea'+i,value=>{getState().empire.network.stores[i].area=Number(value);changed('Delivery area changed');});
  onPill('walkinReserve'+i,value=>{getState().empire.network.stores[i].reserve=Number(value)*5;changed('Walk-in reserve updated');});
  $('fleetUpgrade'+i).onclick=()=>act(()=>upgradeFleet(getState()),'Driver joined the fleet');$('areaUpgrade'+i).onclick=()=>act(()=>expandArea(getState()),'Delivery area expanded');
  $('opPane'+i+'2').innerHTML='<p class="operation-hint" id="managerSummary'+i+'"></p><h4>Team</h4>'+Object.entries(STAFF).map(([id,person])=>'<div class="operation-row"><span><strong>'+person.name+'</strong><small>'+person.trait+'</small><small>'+MANAGERS.find(m=>m.id===id).detail+'</small><small id="staffInfo'+i+id+'"></small></span><button id="assign'+i+id+'"></button></div>').join('')+'<h4>'+REGULARS[i].name+' <span class="operation-muted">'+REGULARS[i].role+'</span></h4><p id="storyTitle'+i+'"></p><div class="relationship" id="relationship'+i+'"></div><div class="operation-row"><span id="storyNeed'+i+'"></span><button id="storyServe'+i+'">Fulfill request</button></div><p class="operation-hint" id="storyHint'+i+'"></p>';
  Object.keys(STAFF).forEach(id=>$('assign'+i+id).onclick=()=>act(()=>assignManager(getState().empire,i,id),STAFF[id].name+' moved to '+name));
  $('storyServe'+i).onclick=()=>act(()=>fulfillStory(getState(),i),REGULARS[i].name+' relationship grew');
  $('opPane'+i+'3').innerHTML='<p class="operation-hint">Your look. No cost or income bonus.</p>'+Object.entries(COSMETICS).map(([key,options])=>pillGroup('style'+i+key,key[0].toUpperCase()+key.slice(1),options,options.map((_,j)=>j),key)).join('')+'<p class="operation-hint" id="neighborhood'+i+'"></p><button id="previewStyle'+i+'">View store</button>';
  Object.keys(COSMETICS).forEach(key=>onPill('style'+i+key,value=>act(()=>customize(getState().empire,i,key,Number(value)),'Store style updated')));
  $('previewStyle'+i).onclick=()=>visit(i,false);
 });
 return {showTab,render(){const state=getState(),p=state.empire,n=p.network;
  BRANCH_NAMES.forEach((_,i)=>{const s=n.stores[i],owned=p.stores[i].level>0;
   // Unopened stores show only Overview; the management tabs appear once the store exists.
   for(let j=1;j<4;j++){$('opTab'+i+j).disabled=!owned;$('opTab'+i+j).hidden=!owned;}if(!owned&&selected[i])showTab(i,0);
   const g=openingStatus(p,i);$('openingLabel'+i).textContent=g.title;$('openingProgress'+i).value=g.progress/g.target*100;$('openingClaim'+i).textContent=s.opening===3?'Established':format(g.reward);$('openingClaim'+i).disabled=!g.ready||!owned;$('openingLabel'+i).parentElement.hidden=!owned;
   $('harvestCount'+i).textContent=Math.floor(s.raw)+'/120 harvest';$('shelfCount'+i).textContent=shelfUsed(s)+'/'+shelfCapacity(p,i)+' shelf spaces';setPill('recipe'+i,String(s.recipe));LINES.forEach((l,j)=>pillButton('recipe'+i,String(j)).disabled=!n.recipes[j]);
   setPill('featured'+i,p.stores[i].featured);PRODUCTS.forEach(f=>pillButton('featured'+i,f).disabled=!owned);pillButton('featured'+i,'exclusive').disabled=!owned||!exclusiveAvailable(p);$('featuredEffect'+i).textContent=({everyday:'For regulars',exclusive:'Reserve · +15% income',boutique:i===1&&p.stores[i].level>=2?'Boutique · +40% income':'For VIPs',express:'Faster service'})[p.stores[i].featured];
   $('craftStatus'+i).textContent=LINES[s.recipe].seconds+'s / item · '+s.sold+' sold';
   LINES.forEach((l,j)=>{$('lineCount'+i+j).textContent=s.stock[j]+' stocked · '+format(l.price);$('shelfAllocation'+i+j).textContent=s.shelves[j];$('shelfLess'+i+j).disabled=s.shelves[j]-5<s.stock[j]||s.shelves[j]<5;$('shelfMore'+i+j).disabled=!n.recipes[j]||shelfUsed(s)+5>shelfCapacity(p,i);if(j){const unlocked=n.recipes[j];$('research'+i+j).hidden=unlocked;$('research'+i+j).textContent='Unlock · '+format(l.research);$('research'+i+j).disabled=state.money<l.research||!p.stores[0].level;$('shelfStepper'+i+j).hidden=!unlocked;}});
   const to=Number(pillValue('transferTo'+i)),reason=transferReason(p,to);$('transferSend'+i).disabled=!!reason;$('transferReason'+i).textContent=reason||'Riverside → '+BRANCH_NAMES[to]+' · '+(24+to*8)+'s';$('importHarvest'+i).disabled=!p.stores[0].level||state.stock[2]<10||n.stores[0].raw+10>120;
   setPill('deliveryArea'+i,String(s.area));[0,1,2].forEach(j=>pillButton('deliveryArea'+i,String(j)).disabled=j>n.area);setPill('walkinReserve'+i,String(s.reserve/5));const delivery=deliveryReason(p,i,Number(pillValue('deliveryLine'+i)));$('deliverySend'+i).disabled=!!delivery;$('deliveryHint'+i).textContent=delivery||s.demand+' delivery requests · stock reserved on dispatch';
   $('routeBadge'+i).textContent=n.jobs.length+'/'+n.fleet+' drivers';$('routes'+i).innerHTML=n.jobs.length?n.jobs.map(job=>'<div class="route"><span>'+BRANCH_NAMES[job.from]+' → '+(job.to<0?'Customers':BRANCH_NAMES[job.to])+'</span><small>'+Math.max(0,Math.ceil(job.duration-job.elapsed))+'s</small><progress max="100" value="'+job.elapsed/job.duration*100+'" aria-label="Delivery progress"></progress></div>').join(''):'<p class="operation-hint">Drivers ready</p>';
   $('fleetLabel'+i).textContent=n.fleet+' driver'+(n.fleet===1?'':'s');$('fleetUpgrade'+i).textContent=n.fleet>=3?'Fully staffed':'+ Driver '+format(2000*n.fleet*n.fleet);$('fleetUpgrade'+i).disabled=n.fleet>=3||state.money<2000*n.fleet*n.fleet;$('areaUpgrade'+i).textContent=n.area===2?'Citywide':format([3000,12000][n.area]);$('areaUpgrade'+i).disabled=n.area===2||state.money<[3000,12000][n.area]||!p.stores[2].level;
   Object.keys(STAFF).forEach(id=>{const location=p.stores.findIndex(s=>s.manager===id);$('staffInfo'+i+id).textContent=STAFF[id].specialty+' '+staffLevel(n,id)+'/5 · '+Math.floor(n.staff[id].xp)+' XP'+(location>=0?' · '+BRANCH_NAMES[location]:'');$('assign'+i+id).textContent=location===i?'Assigned':'Move here';$('assign'+i+id).disabled=location===i||!owned;});
   const mgr=MANAGERS.find(m=>m.id===p.stores[i].manager);$('managerSummary'+i).textContent=(p.stores[i].manager==='none'?'No manager assigned.':mgr.name+' is managing · '+mgr.detail+'.')+' One store per specialist — assigning below moves them from elsewhere.';
   const story=storyStatus(p,i);$('storyTitle'+i).textContent=story.title;$('relationship'+i).textContent=['New face','Acquaintance','Friend','Regular'][s.relationship]+' · '+s.relationship+'/3';$('storyNeed'+i).textContent=s.relationship===3?'Story complete':story.need+' '+LINES[story.line].name;$('storyServe'+i).disabled=!story.ready;$('storyServe'+i).hidden=s.relationship===3;$('storyHint'+i).textContent=s.relationship===3?'Returns to the shop as a familiar face':s.storyWait>0?'Returns in '+Math.ceil(s.storyWait)+'s':format(story.reward)+' · +5 loyalty';
   Object.keys(COSMETICS).forEach(key=>setPill('style'+i+key,String(s.cosmetics[key])));$('neighborhood'+i).textContent='Neighborhood: '+['Quiet block','New neighbors','Lively street','Local destination'][neighborhood(p,i)];
  });
 }};
}
