import {BRANCH_NAMES,LINES,STAFF,REGULARS,COSMETICS,atmosphere,staffLevel,shelfCapacity,shelfUsed,allocateShelf,developProduct,chooseRecipe,customize,importHarvest,transferReason,sendTransfer,deliveryReason,dispatchDelivery,upgradeFleet,expandArea,openingStatus,claimOpening,storyStatus,fulfillStory,journal,flagshipStatus,claimFlagship,branchBottleneck,neighborhood} from './operations.js';
export function mountOperations({getState,format,changed,visit,mainFlow}){
 const $=id=>document.getElementById(id),selected=[0,0,0];
 const act=(fn,message)=>{const result=fn();if(result)changed(message);return result;};
 const selector=(id,label,options)=>'<label for="'+id+'">'+label+'</label><select id="'+id+'">'+options.map((name,j)=>'<option value="'+j+'">'+name+'</option>').join('')+'</select>';
 function showTab(i,index){selected[i]=index;['overview','stock','people','style'].forEach((name,j)=>{$('opTab'+i+j).setAttribute('aria-pressed',String(j===index));$('opPane'+i+j).hidden=j!==index;});}
 BRANCH_NAMES.forEach((name,i)=>{
  const body=$('branchBody'+i),overview=document.createElement('div');overview.id='opPane'+i+'0';overview.className='op-pane';while(body.firstChild)overview.appendChild(body.firstChild);body.appendChild(overview);
  const nav=document.createElement('nav');nav.className='operation-tabs';nav.setAttribute('aria-label',name+' management');const tabIcons=['<path d="M4 10.5 12 4l8 6.5V20H4z M9 20v-6h6v6"/>','<path d="M4 8h16v11H4zM4 8l3-4h10l3 4M12 4v4"/>','<circle cx="9" cy="8" r="3"/><circle cx="16" cy="9" r="2.4"/><path d="M3 20a6 6 0 0 1 12 0M13 20a4.5 4.5 0 0 1 8 0"/>','<path d="M5 17c2 0 3-1 3-3l7-7 3 3-7 7c-2 0-3 1-3 3-2 0-3-1-3-3ZM14 6l3 3"/>'];nav.innerHTML=['Overview','Stock','People','Style'].map((t,j)=>'<button id="opTab'+i+j+'" aria-pressed="'+(j===0)+'"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+tabIcons[j]+'</svg><em>'+t+'</em></button>').join('');const header=document.createElement('div');header.className='branch-sticky-header';const toggle=$('branchToggle'+i);toggle.before(header);header.append(toggle,nav);nav.hidden=body.hidden;
  ['Stock','People','Style'].forEach((_,j)=>{const pane=document.createElement('div');pane.id='opPane'+i+(j+1);pane.className='op-pane';pane.hidden=true;body.appendChild(pane);});
  [0,1,2,3].forEach(j=>$('opTab'+i+j).onclick=()=>showTab(i,j));
  const opening=document.createElement('div');opening.className='opening-task';opening.innerHTML='<span id="openingLabel'+i+'"></span><button id="openingClaim'+i+'"></button><progress id="openingProgress'+i+'" max="100" aria-label="Grand-opening goal"></progress>';
  overview.prepend(opening);$('openingClaim'+i).onclick=()=>act(()=>claimOpening(getState(),i),'Grand-opening goal complete');
  $('opPane'+i+'1').innerHTML='<div class="operation-stats"><strong id="harvestCount'+i+'"></strong><span id="shelfCount'+i+'"></span></div>'+selector('recipe'+i,'Make',LINES.map(l=>l.name+' · '+l.raw+' harvest'))+'<p class="operation-hint" id="craftStatus'+i+'"></p><div class="shelf-list">'+LINES.map((l,j)=>'<div class="shelf-row"><div><strong>'+l.name+'</strong><small id="lineCount'+i+j+'"></small></div><div class="shelf-stepper"><button id="shelfLess'+i+j+'" aria-label="Remove five '+l.name+' shelf spaces">−</button><span id="shelfAllocation'+i+j+'"></span><button id="shelfMore'+i+j+'" aria-label="Add five '+l.name+' shelf spaces">+</button></div></div>').join('')+'</div><details class="operation-details"><summary>Develop products</summary>'+LINES.slice(1).map((l,j)=>'<div class="operation-row"><span>'+l.name+'<small>'+l.raw+' harvest → '+format(l.price)+' per item</small></span><button id="research'+i+(j+1)+'"></button></div>').join('')+'</details><details class="operation-details"><summary>Transfers &amp; deliveries <span id="routeBadge'+i+'"></span></summary><div class="operation-row"><span>Riverside harvest</span><button id="importHarvest'+i+'">Import 10</button></div><p class="operation-hint">Imports use main-shop harvest. Vans and product lines run while playing; base income continues offline.</p>'+selector('transferTo'+i,'Send 10 harvest from Riverside',['Old Town','City Center'])+'<button class="operation-primary" id="transferSend'+i+'">Send transfer</button><p id="transferReason'+i+'" class="operation-hint"></p><div class="branch-choices"><div>'+selector('deliveryLine'+i,'Deliver 5',LINES.map(l=>l.name))+'</div><div>'+selector('deliveryArea'+i,'Area',['Local','District','Citywide'])+'</div></div><div class="branch-choices"><div>'+selector('walkinReserve'+i,'Keep for walk-ins',['0 per product','5 per product','10 per product'])+'</div><div><label>Driver dispatch</label><button class="operation-primary" id="deliverySend'+i+'">Dispatch</button></div></div><p class="operation-hint" id="deliveryHint'+i+'"></p><div id="routes'+i+'" class="route-list"></div><div class="operation-row"><span id="fleetLabel'+i+'"></span><button id="fleetUpgrade'+i+'"></button></div><div class="operation-row"><span>Delivery coverage</span><button id="areaUpgrade'+i+'"></button></div></details>';
  $('recipe'+i).onchange=e=>act(()=>chooseRecipe(getState().empire,i,Number(e.target.value)),'Production line changed');
  LINES.forEach((l,j)=>{[-1,1].forEach(dir=>$('shelf'+(dir<0?'Less':'More')+i+j).onclick=()=>act(()=>allocateShelf(getState().empire,i,j,dir*5),'Shelf plan updated'));if(j)$('research'+i+j).onclick=()=>act(()=>developProduct(getState(),j),l.name+' developed');});
  $('transferTo'+i).value=String(i===2?1:0);
  $('transferSend'+i).onclick=()=>act(()=>sendTransfer(getState().empire,Number($('transferTo'+i).value)+1),'Van dispatched from Riverside');
  $('importHarvest'+i).onclick=()=>act(()=>importHarvest(getState()),'10 harvest moved to Riverside');
  $('deliverySend'+i).onclick=()=>act(()=>dispatchDelivery(getState().empire,i,Number($('deliveryLine'+i).value)),'Driver dispatched');
  $('deliveryArea'+i).onchange=e=>{getState().empire.network.stores[i].area=Number(e.target.value);changed('Delivery area changed');};
  $('walkinReserve'+i).onchange=e=>{getState().empire.network.stores[i].reserve=Number(e.target.value)*5;changed('Walk-in reserve updated');};
  $('fleetUpgrade'+i).onclick=()=>act(()=>upgradeFleet(getState()),'Driver joined the fleet');$('areaUpgrade'+i).onclick=()=>act(()=>expandArea(getState()),'Delivery area expanded');
  $('opPane'+i+'2').innerHTML='<h4>Team</h4>'+Object.entries(STAFF).map(([id,person])=>'<div class="operation-row"><span><strong>'+person.name+'</strong><small>'+person.trait+'</small><small id="staffInfo'+i+id+'"></small></span><button id="assign'+i+id+'"></button></div>').join('')+'<h4>'+REGULARS[i].name+' <span class="operation-muted">'+REGULARS[i].role+'</span></h4><p id="storyTitle'+i+'"></p><div class="relationship" id="relationship'+i+'"></div><div class="operation-row"><span id="storyNeed'+i+'"></span><button id="storyServe'+i+'">Fulfill request</button></div><p class="operation-hint" id="storyHint'+i+'"></p>';
  Object.keys(STAFF).forEach(id=>$('assign'+i+id).onclick=()=>{const p=getState().empire;p.stores.forEach(s=>{if(s.manager===id)s.manager='none';});p.stores[i].manager=id;changed(STAFF[id].name+' moved to '+name);});
  $('storyServe'+i).onclick=()=>act(()=>fulfillStory(getState(),i),REGULARS[i].name+' relationship grew');
  $('opPane'+i+'3').innerHTML='<p class="operation-hint">Your look. No cost or income bonus.</p><div class="branch-choices">'+Object.entries(COSMETICS).map(([key,options])=>'<div>'+selector('style'+i+key,key[0].toUpperCase()+key.slice(1),options)+'</div>').join('')+'</div><p class="operation-hint" id="neighborhood'+i+'"></p><button id="previewStyle'+i+'">View store</button>';
  Object.keys(COSMETICS).forEach(key=>$('style'+i+key).onchange=e=>act(()=>customize(getState().empire,i,key,Number(e.target.value)),'Store style updated'));
  $('previewStyle'+i).onclick=()=>visit(i,false);
 });
 const today=document.querySelector('[data-empire-section=today]'),extension=document.createElement('div');extension.className='operations-today';extension.innerHTML='<details class="operation-details"><summary>Business flow <span id="dayPhase"></span></summary><div class="operation-row"><span id="mainBottleneck"></span><button id="mainBottleneckAction">Improve</button></div>'+BRANCH_NAMES.map((name,i)=>'<div class="operation-row"><span>'+name+'<small id="branchBottleneck'+i+'"></small></span><button id="fixBottleneck'+i+'"></button></div>').join('')+'</details><details class="operation-details"><summary>Collection journal <span id="journalCount"></span></summary><div id="journalEntries"></div></details><details class="operation-details"><summary>Flagship status <span id="flagshipCount"></span></summary><div id="flagshipChecks"></div><button class="operation-primary" id="claimFlagship">Earn flagship status</button></details>';
 today.appendChild(extension);$('claimFlagship').onclick=()=>act(()=>claimFlagship(getState()),'Flagship status earned');$('mainBottleneckAction').onclick=()=>mainFlow(true);
 BRANCH_NAMES.forEach((_,i)=>$('fixBottleneck'+i).onclick=()=>{const p=getState().empire,b=branchBottleneck(p,i);const target=b.name==='Supply'?0:i;visit(target,true);showTab(target,b.tab==='stock'?1:0);});
 let journalCache='',flagCache='';
 return {showTab,render(){const state=getState(),p=state.empire,n=p.network;
  $('dayPhase').textContent=atmosphere(n).name;$('mainBottleneck').textContent=mainFlow(false);
  BRANCH_NAMES.forEach((_,i)=>{const s=n.stores[i],owned=p.stores[i].level>0;
   // Unopened stores show only Overview; the management tabs appear once the store exists.
   for(let j=1;j<4;j++){$('opTab'+i+j).disabled=!owned;$('opTab'+i+j).hidden=!owned;}if(!owned&&selected[i])showTab(i,0);
   const g=openingStatus(p,i);$('openingLabel'+i).textContent=g.title;$('openingProgress'+i).value=g.progress/g.target*100;$('openingClaim'+i).textContent=s.opening===3?'Established':format(g.reward);$('openingClaim'+i).disabled=!g.ready||!owned;$('openingLabel'+i).parentElement.hidden=!owned;
   $('harvestCount'+i).textContent=Math.floor(s.raw)+'/120 harvest';$('shelfCount'+i).textContent=shelfUsed(s)+'/'+shelfCapacity(p,i)+' shelf spaces';$('recipe'+i).value=String(s.recipe);Array.from($('recipe'+i).options).forEach((o,j)=>o.disabled=!n.recipes[j]);
   $('craftStatus'+i).textContent=LINES[s.recipe].seconds+'s / item · '+s.sold+' sold';
   LINES.forEach((l,j)=>{$('lineCount'+i+j).textContent=s.stock[j]+' stocked · '+format(l.price);$('shelfAllocation'+i+j).textContent=s.shelves[j];$('shelfLess'+i+j).disabled=s.shelves[j]-5<s.stock[j]||s.shelves[j]<5;$('shelfMore'+i+j).disabled=!n.recipes[j]||shelfUsed(s)+5>shelfCapacity(p,i);if(j){$('research'+i+j).textContent=n.recipes[j]?'Developed':format(l.research);$('research'+i+j).disabled=n.recipes[j]||state.money<l.research||!p.stores[0].level;}});
   const to=Number($('transferTo'+i).value)+1,reason=transferReason(p,to);$('transferSend'+i).disabled=!!reason;$('transferReason'+i).textContent=reason||'Riverside → '+BRANCH_NAMES[to]+' · '+(24+to*8)+'s';$('importHarvest'+i).disabled=!p.stores[0].level||state.stock[2]<10||n.stores[0].raw+10>120;
   $('deliveryArea'+i).value=String(s.area);Array.from($('deliveryArea'+i).options).forEach((o,j)=>o.disabled=j>n.area);$('walkinReserve'+i).value=String(s.reserve/5);const delivery=deliveryReason(p,i,Number($('deliveryLine'+i).value));$('deliverySend'+i).disabled=!!delivery;$('deliveryHint'+i).textContent=delivery||s.demand+' delivery requests · stock reserved on dispatch';
   $('routeBadge'+i).textContent=n.jobs.length+'/'+n.fleet+' drivers';$('routes'+i).innerHTML=n.jobs.length?n.jobs.map(job=>'<div class="route"><span>'+BRANCH_NAMES[job.from]+' → '+(job.to<0?'Customers':BRANCH_NAMES[job.to])+'</span><small>'+Math.max(0,Math.ceil(job.duration-job.elapsed))+'s</small><progress max="100" value="'+job.elapsed/job.duration*100+'" aria-label="Delivery progress"></progress></div>').join(''):'<p class="operation-hint">Drivers ready</p>';
   $('fleetLabel'+i).textContent=n.fleet+' driver'+(n.fleet===1?'':'s');$('fleetUpgrade'+i).textContent=n.fleet>=3?'Fully staffed':'+ Driver '+format(2000*n.fleet*n.fleet);$('fleetUpgrade'+i).disabled=n.fleet>=3||state.money<2000*n.fleet*n.fleet;$('areaUpgrade'+i).textContent=n.area===2?'Citywide':format([3000,12000][n.area]);$('areaUpgrade'+i).disabled=n.area===2||state.money<[3000,12000][n.area]||!p.stores[2].level;
   Object.keys(STAFF).forEach(id=>{const location=p.stores.findIndex(s=>s.manager===id);$('staffInfo'+i+id).textContent=STAFF[id].specialty+' '+staffLevel(n,id)+'/5 · '+Math.floor(n.staff[id].xp)+' XP'+(location>=0?' · '+BRANCH_NAMES[location]:'');$('assign'+i+id).textContent=location===i?'Assigned':'Move here';$('assign'+i+id).disabled=location===i||!owned;});
   const story=storyStatus(p,i);$('storyTitle'+i).textContent=story.title;$('relationship'+i).textContent=['New face','Acquaintance','Friend','Regular'][s.relationship]+' · '+s.relationship+'/3';$('storyNeed'+i).textContent=s.relationship===3?'Story complete':story.need+' '+LINES[story.line].name;$('storyServe'+i).disabled=!story.ready;$('storyServe'+i).hidden=s.relationship===3;$('storyHint'+i).textContent=s.relationship===3?'Returns to the shop as a familiar face':s.storyWait>0?'Returns in '+Math.ceil(s.storyWait)+'s':format(story.reward)+' · +5 loyalty';
   Object.keys(COSMETICS).forEach(key=>$('style'+i+key).value=String(s.cosmetics[key]));$('neighborhood'+i).textContent='Neighborhood: '+['Quiet block','New neighbors','Lively street','Local destination'][neighborhood(p,i)];
   const b=branchBottleneck(p,i);$('branchBottleneck'+i).textContent=b.name;$('fixBottleneck'+i).textContent=b.action;
  });
  const entries=journal(state),found=entries.filter(e=>e.found).length;$('journalCount').textContent=found+'/'+entries.length;
  const signature=entries.map(e=>Number(e.found)).join('');if(signature!==journalCache){journalCache=signature;$('journalEntries').innerHTML=['Strains','Products','Regulars','Milestones','Souvenirs'].map(group=>'<h4>'+group+'</h4>'+entries.filter(e=>e.group===group).map(e=>'<div class="journal-entry '+(e.found?'discovered':'')+'"><span>'+e.name+'</span><small>'+(e.found?'Found':'Undiscovered')+'</small></div>').join('')).join('');}
  const flagship=flagshipStatus(state),flagSignature=JSON.stringify(flagship);$('flagshipCount').textContent=flagship.claimed?'Earned':flagship.checks.filter(c=>c.value>=c.total).length+'/4';if(flagSignature!==flagCache){flagCache=flagSignature;$('flagshipChecks').innerHTML=flagship.checks.map(c=>'<div class="flagship-check"><span>'+c.name+'</span><strong>'+c.value+'/'+c.total+'</strong><progress aria-label="'+c.name+'" max="'+c.total+'" value="'+c.value+'"></progress></div>').join('');}$('claimFlagship').disabled=flagship.claimed||!flagship.ready;$('claimFlagship').textContent=flagship.claimed?'Flagship earned':'Earn flagship status';
 }};
}
